name: academia_flow
description: "UniStudy Organizer is your all-in-one academic companion, empowering university students to master their subjects with organized notes, multimedia resources, brainstorming tools, and self-quizzes, all accessible offline."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  file_picker: '>=8.1.2'
  image_picker: '>=1.1.2'
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
